WIP: Improve builder
ros-realtime/linux-real-time-kernel-builder pull request #7
Opened 2021-06-20 15:48 UTC by LanderU

2021-06-20 15:52 UTC, LanderU commented
FYI @carlossvg

2021-06-21 05:50 UTC, carlossvg approved these changes
LGTM

2021-08-05 09:42 UTC, razr requested changes

2021-08-05 09:42 UTC, razr commented on Dockerfile
> +ENV LANG "C fakeroot debian/rules printenv"
```fakeroot debian/rules printenv``` was not export, it was just a command

2021-08-13 13:01 UTC, LanderU commented on Dockerfile
> +ENV LANG "C fakeroot debian/rules printenv"
@razr, sorry for the silence! You're right I will fix it.

2022-06-17 21:06 UTC, razr commented
@LanderU do we still need to work on this PR or we can close it?

2022-06-18 21:29 UTC, LanderU commented
@razr, no, closing here.

2022-06-18 21:29 UTC, closed without merging